### ISSUE TITLE
[Webpack 4, style-loader 0.20.3] Styles not imported in <head> tag

### ISSUE THREAD

**Issue by marem-bzh** [webpack-contrib/style-loader#312] opened 2018-04-03 10:59 UTC
I started using style-loader a few days ago to include it in a boilerplate for my JavaScript projets and my teams.

Everything seemed fine in development mode, but everytime I build my projects for production, absolutely no CSS is included in `<style></style>`.

Here's my configuration : 
https://gist.github.com/marem-bzh/3ed3f98bca42b0c762ef48faae5dd88e

I didn't provide my **webpack.dev.js**, as **webpack.prod.js** works too whenever I set `mode: 'development'` instead of `mode: 'production'`.

I'm currently running style-loader 0.20.3 on Webpack 4 under Node 8.9.4 and Windows 10. Any idea why the production mode would impact ? It doesn't prevent me from working as I can launch my dev server and build in webpack's dev mode, but it is annoying not to be able to build properly.

I'm not really used to requesting help online, so feel free to correct my manners if I misbehaved. I am not exactly sure whether it's a bug or just a mistake from me.

Cheers mates.

**Comment by evilebottnawi** [comment] 2018-04-17 09:52
@marem-bzh can you create minimum reproducible test repo?

**Comment by Offirmo** [comment] 2018-04-17 22:36
@marem-bzh a silly possibility, but that happened to me :) : did you properly import your CSS from your JS file? If not, there is no way webpack will pick it.

Just in case.

**Comment by rcorichard** [comment] 2018-04-19 22:05
I'm having the same problem and started since I migrated to webpack 4.

**Comment by amourzenkov-sc** [comment] 2018-04-25 10:58
I've had the same problem.  In my case the issue was not with "style-loader" but with `"sideEffects": false` in *package.json* - which is applicable in `mode: 'production'` only.  See [Webpack Tree Shaking](https://webpack.js.org/guides/tree-shaking/) for details.

**Comment by evilebottnawi** [comment] 2018-04-25 11:13
Somebody can create minimum reproducible test repo? We have use `style-loader` in dev and prod mode and all works fine.

@amourzenkov-sc Also remove `singleton` options. Because `style-loader` self determine when we have old browser https://github.com/webpack-contrib/style-loader/blob/892cba5ad5d654e1db027b96f82caf683cbd29bb/lib/addStyles.js#L77.

In future major release this option will be removed. Thanks!

**Comment by msz** [comment] 2018-07-12 16:36
I'm having the same issue, and removing `"sideEffects": false` from `package.json` as @amourzenkov-sc suggested fixes it.

**Comment by Souhail-5** [comment] 2018-07-19 23:31
If by removing the `"sideEffects"` property your issue is resolved, it means that your CSS is considered as a "side effect" by webpack (which is not bad).

To **keep the Tree Shaking while resolving your issue**, keep the `"sideEffects"` property to `false` in your `package.json` and add a specific rule for CSS files in your `webpack.prod.js` config:

```
module: {
  rules: [
    {
      test: /\.css$/,
      sideEffects: true,
    },
  ]
},
```

For more information:

ℹ️ **Tree Shaking**: "You can imagine your application as a tree. The source code and libraries you actually use represent the green, living leaves of the tree. Dead code represents the brown, dead leaves of the tree that are consumed by autumn. In order to get rid of the dead leaves, you have to shake the tree, causing them to fall." ([source](https://webpack.js.org/guides/tree-shaking/#conclusion))
ℹ️ **A "side effect"**: "A "side effect" is defined as code that performs a special behavior when imported, other than exposing one or more exports. An example of this are polyfills, which affect the global scope and usually do not provide an export." ([source](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free))

**I guess webpack drops all undeclared "side effects" when in production mode. Webpack Tree Shaking considers them like "dead leaves".**

**Comment by qingyun1029** [comment] 2018-12-11 16:32
> I'm having the same problem and started since I migrated to webpack 4.

I had the same problem.

{
  "devDependencies": {
    "style-loader": "^0.23.1",
    "webpack": "^4.27.1"
  }
}

**Comment by evilebottnawi** [comment] 2018-12-11 17:02
@qingyun1029 please create minimum reproducible test repo

**Comment by qingyun1029** [comment] 2018-12-12 12:20
@evilebottnawi 

Thanks !  I rewrote a small [example](https://gitee.com/qingyun1029/webpack-for-multiple-page-demo), built and still did not generate style tags, on the HTML page.

1. git clone git@gitee.com:qingyun1029/webpack-for-multiple-page-demo.git
2. npm install
3. npm run build

**Comment by evilebottnawi** [comment] 2018-12-12 12:23
@qingyun1029 thanks, in near future we will refactor `style-loader` and i think we fix this problem

**Comment by adeka** [comment] 2019-03-14 16:54
> I've had the same problem. In my case the issue was not with "style-loader" but with `"sideEffects": false` in _package.json_ - which is applicable in `mode: 'production'` only. See [Webpack Tree Shaking](https://webpack.js.org/guides/tree-shaking/) for details.

that's bizarre. never would have guessed thats why my css wasn't building.

**Comment by tenorius** [comment] 2019-04-21 17:59
I'm having the same problem:
"devDependencies": {
    "style-loader": "^0.23.1",
    "webpack": "^4.30.0",
}
The sideEffects tip did not work for me. Any other suggestions?

**Comment by evilebottnawi** [comment] 2019-08-02 15:47
Here docs about sideEffects https://webpack.js.org/guides/tree-shaking/, anyway if you have problem, please open new issue with **reproducible test repo**, thanks

**Comment by evilebottnawi** [comment] 2019-08-02 15:47
Also it is related more to webpack than style-loader

**Closed by evilebottnawi** 2019-08-02 15:47 UTC
Labels: flag: Needs more info
