### ISSUE TITLE
Singleton + sourcemap do not work together

### ISSUE THREAD

**Issue by edi9999** [webpack-contrib/style-loader#134] opened 2016-07-11 13:56 UTC
if I set "singleton&sourcemap" in my webpack options, it seems that sourcemap doesn't work anymore (eg no sourcemaps are generated at all)

It seems here : https://github.com/webpack/style-loader/blob/cff991ea90a416b44f4fa75c9cd6e1eb2d18b977/addStyles.js#L146 that both options cannot be used together.

Is this expected, and are they any workarounds around this ?

Without the singleton property, our pages css doesn't show well at the start, so we would like to use both sourcemap and singleton

**Comment by niksy** [comment] 2017-02-03 16:21
Also looking for this. Is there any technical difficulty for implementing this?

**Comment by evilebottnawi** [comment] 2017-12-07 12:24
@niksy yes, it is technical difficulty, but if you have idea how to solve this PR welcome

**Comment by garygreen** [comment] 2018-03-14 13:47
This is annoying because using the `singleton` option really helps improves rendering performance when developing so I tend to always have it enabled purely for that reason. See https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing for more info.

If that can be avoided in some way and have sourcemaps too, that would be ideal (maybe not for IE developers, but that's a fair compromise!)

**Comment by evilebottnawi** [comment] 2019-07-29 11:47
It is limitation for `singleton` and can be unfortunately won't fix, we need update docs about it

**Comment by evilebottnawi** [comment] 2019-08-03 15:26
In theory it is possible, but it is create overload in runtime code because we need merge source maps and it is not cheap for client computer, also we don't recommend use singleton due it is only for old browsers, if you have problem with performance using multiple tags better open issue with reproducible example (also you should consider extracting css). Sorry, mark as won't fix. Anyway we are open for PRs and can revisit this.

**Closed by evilebottnawi** 2019-08-03 15:26 UTC
Labels: priority: 5 (nice to have), severity: 5 (confusing), type: Documentation
