### ISSUE TITLE
Is it possible to supply style/url a public url that does not exist at build time?

### ISSUE THREAD

**Issue by localnerve** [webpack-contrib/style-loader#91] opened 2015-11-15 03:41 UTC
I would like to use the style/url loader to inject a stylesheet link into the DOM to a public url to an asset that was already built (not by webpack).

In my case, the public directory does not exist at build time.

Webpack complains if I supply style/url a public path to a web asset (same origin), saying the file doesn't exist (because it doesn't).

Is it possible to supply a public url that does not exist at build time to style/url?
It seems by [this](https://github.com/webpack/style-loader/blob/6664a954d5a77a6cb2ef1ad33db936e41eb78bf4/url.js#L13) that style/url forces it to resolve as a physical file before it can be used in the link.

Thanks in advance for any information on this.

**Comment by michael-ciniawsky** [comment] 2017-03-17 00:45
@localnerve Is this still relevant? Did you find a solution in the meantime? Why not referencing the the public url in index.html directly? 😛

**Comment by michael-ciniawsky** [comment] 2017-03-17 01:03
@localnerve Maybe related #16

**Comment by localnerve** [comment] 2017-03-17 16:16
@michael-ciniawsky The public url IS referenced in the html with this issue. Restating the crux:
> The requirement of this component that a public url refers to a physical, build-time location. This requirement is enforced [in the `require`](https://github.com/webpack-contrib/style-loader/blob/master/url.js#L13) that will fail if there is no physical file there.

The work around is to not use this component if you have style assets that map to anything other than a physical, build time location. I might have some time to work on this if there is interest.

Problem stated another way in example:
> '/public/style.css' referenced in 'index.html' actually exists at '/assets/styles/style.css' on the server, served by a static middleware.

**Comment by michael-ciniawsky** [comment] 2017-03-17 23:34
@localnerve I understand, is that issue for `style-loader` in particular (it's code base) or more of an general webpack/`require()` issue? Please go ahead if you have time, any solution/proposal/discussion about it highly welcome 😛

**Comment by michael-ciniawsky** [comment] 2017-03-26 22:44
@localnerve I'm closing this for now since it seems not directly related to `style-loader`, if anything comes to your mind or you have another regression please open a new issue 🙃

**Closed by michael-ciniawsky** 2017-03-26 22:44 UTC
Labels: enhancement, pr
